# Generated by Django 5.0.2 on 2024-03-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votinwebsite', '0003_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='partyinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofparty', models.CharField(max_length=100)),
                ('numberofvote', models.CharField(max_length=100)),
            ],
        ),
    ]
