# Generated by Django 5.0.2 on 2024-03-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votinwebsite', '0004_partyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partyname', models.CharField(max_length=100)),
                ('votecount', models.CharField(max_length=100)),
            ],
        ),
    ]
